name: testing

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches:
      - master
      - lispci/master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: containers.common-lisp.net/cl-docker-images/${{matrix.l}}:${{matrix.IMAGE_TAG}}

    strategy:
      matrix:
        os: [ubuntu-latest]
        # just going to try to get ONE lisp to work first
        # can't run CMUCL on GitHub actions.
        # ccl's ASDF seems to be having trouble with source initialization 
        l: [abcl, allegro, clisp, ecl, sbcl] # ccl, cmucl (probably not the last).
        IMAGE_TAG: [latest]
        include:
          - l: clasp
            IMAGE_TAG: "b14e329f49998275579926da2a737885ceb2cea7"
          - l: allegro
            IMAGE_TAG: latest
            variant: modern
          - l: abcl
            IMAGE_TAG: 1.7.1-jdk8 # FIXME: this is likely obsolete

    env:
      GITHUB_ACTION: true
      I_AGREE_TO_ALLEGRO_EXPRESS_LICENSE: yes
      QUICKLISP_SETUP: /github/home/quicklisp/setup.lisp
      GITHUB_WORKSPACE: 

    steps:
    - uses: actions/checkout@v2

    - name: Checkout submodules
      shell: bash
      run: |
        git config --global --add safe.directory ${GITHUB_WORKSPACE} && \
        git submodule update --init --recursive

    - name: collect ASDF
      shell: bash
      if: ${{ matrix.l == 'clisp' }}
      run: |
        mkdir -p /usr/local/share/common-lisp/asdf && \
        pushd /usr/local/share/common-lisp/asdf && \
        curl https://asdf.common-lisp.dev/archives/asdf.lisp > asdf.lisp

    - name: prepare quicklisp
      shell: bash
      run: |
        install-quicklisp && \
        if [ ! -f ${{ env.QUICKLISP_SETUP }} ]; then \
            echo "Did not find Quicklisp setup file where expected: ${QUICKLISP_SETUP}"; \
            find / -name 'quicklisp' -type d ; \
        fi

    - name: test build
      shell: bash
      run: |
        ./run-tests.sh -c ${{ matrix.l }} || ${{ matrix.l == 'clisp' }}
        # no idea how to get FiveAM to build clean on clisp

    - name: save build output
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: ${{matrix.l}}-${{matrix.IMAGE_TAG}}-build-output.text
        path: build/results/${{matrix.l}}-load.text

    - name: tests
      shell: bash
      run: |
        ./run-tests.sh ${{ matrix.l }}

    - name: save test output
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: ${{matrix.l}}-${{matrix.IMAGE_TAG}}-test-output.text
        path: build/results/${{matrix.l}}-test.text
